### ISSUE TITLE
problem with breakpoints props

### ISSUE THREAD

**Issue by metab0x** [glidejs/vue-glide#3]
I'm trying to pass breakpoints props to vue-glide  without success. On small screens the number of slides doesn't change.

```

 <vue-glide

	:autoplay="2000"
	:breakpoints="{'800px':{perView:1},'1200px':{perView:4}}">
	<vue-glide-slide  v-for="index in 10" :key="index">
		Test slide {{index}}
	</vue-glide-slide>

</vue-glide>
```

According to code comments from @glidejs/glide/dist/glide.js  it should be such object :
```
  /**
     * Collection of options applied at specified media breakpoints.
     * For example: display two slides per view under 800px.
     * `{
     *   '800px': {
     *     perView: 2
     *   }
     * }`
     */
```
Version without px units as in official docs didn't help.
https://glidejs.com/docs/components/breakpoints/

```

 <vue-glide

	:autoplay="2000"
	:breakpoints="{800:{perView:1},1200px:{perView:4}}">
	<vue-glide-slide  v-for="index in 10" :key="index">
		Test slide {{index}}
	</vue-glide-slide>

</vue-glide>
```

**Comment by metab0x** [comment]
I figured it out.  In the Glide.vue component breakpoints prop wasn't assigned to options object.
I added fix: ` breakpoints:this.breakpoints,`  around line 181 and it works.

**Comment by jedrzejchalubek** [comment]
Hello, `vue-glide` is still in WIP state. Things may not work as expected as it is not a stable code. Sorry.
