### ISSUE TITLE
What do you think about it?

### ISSUE THREAD

**Issue by coderdiaz** [glidejs/vue-glide#4]
Hi @jedrzejchalubek ,
What do you think about to collaborate with @antonreshetov for create an official package?

Check it out:
https://github.com/antonreshetov/vue-glide

:)

**Comment by adrienbkr** [comment]
Hi @coderdiaz and @antonreshetov,
Why you don't officialize your vue-glide project ?

**Comment by antonreshetov** [comment]
Hi @adrienbkr,
What do you mean by officialize?

Only @jedrzejchalubek as the author of glidejs library can create the wrapper over glidejs for vue and call it official. 

Other projects will be considered as developed by the community.
